package com.maths;

public class Exception_Task {
	public static void main(String[] args) {
		
	
	try {
		int a=3/0;
		System.out.println(a);
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}

	}
}

