package com.maths;

public class Exception_Task {
	public static void main(String[] args) {
		
	
	try {
		try {
			int a=3/0;
			System.out.println(a);
		} catch (ArithmeticException e) {
			e.printStackTrace();
		}
	} catch (Exception a) {
		a.printStackTrace();
	}

	}
}

